import { authenticated } from "../../middlewares/authenticated";
import { authorizeRoles } from "../../middlewares/authorized";
import { catchAsync } from "../../utils/catchAsync";
import AuthRoute from "./auth";
import adminRouter from "./admin"; 
import leaderRouter from "./leader";
import salesRouter from "./sales";
import statusRouter from "./status";
import targetRouter from "./target";
import visitsRouter from "./visits";
import wishListRouter from "./wishList";
import dashboardRouter from "./dashboard";
import RequestsRouter from "./requests";
import productsRouter from "./products";
import { Router } from "express";
const route = Router();
route.use("/auth", catchAsync(AuthRoute));
route.use(authenticated, authorizeRoles("admin", "leader", "sales"));
route.use("/leader", catchAsync(leaderRouter));
route.use("/sales", catchAsync(salesRouter));
route.use("/visit_status", catchAsync(statusRouter));
route.use("/target", catchAsync(targetRouter));
route.use("/admins", catchAsync(adminRouter));
route.use("/visits", catchAsync(visitsRouter));
route.use("/wish_list", catchAsync(wishListRouter));
route.use("/dashboard", catchAsync(dashboardRouter));
route.use("/status_requests", catchAsync(RequestsRouter));
route.use("/products", catchAsync(productsRouter));
export default route;
